version: 2
jobs:
  success_job:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - run: echo "success"

workflows:
  version: 2
  tagged-build:
    jobs:
      - success_job:
          filters:
            branches:
              only: 
                - gh-pages