version: 2
jobs:
  deploy_gh_pages:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: ls

workflows:
  version: 2
  tagged-build:
    jobs:
      - deploy_gh_pages:
          filters:
            branches:
              only: 
                - website